version: '3.1'

services:

  wordpress:
    depends_on:
      - mysql
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wp:/var/www/html

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - wp-data:/var/lib/mysql

  phpmyadmin:
    depends_on:
        - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
    ports:
     - 8081:80
    links:
      - mysql:db

volumes:
  wp-data: